---
header_logo_url: /images/logo.png
header_logo_text: 'World Auchenorhyncha Database'
header_links:
  - label: Home
    link: /

  - label: About
    link: /about

  - label: Recent
    link: /recent

  - label: Help
    link: /help
