taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:descendants
          - panel:nomenclature

        - - id: panel:map
            bind:
              cluster: false
          - panel:type
          - panel:type-specimen
          - panel:keys
          - panel:etymology
          - panel:content
          - panel:nomenclature-references
          - panel:statistics
  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  biological_associations:
    panels:
      - - - panel:biological-associations
  inaturalist:
    label: 'iNaturalist'
    rank_group: ['GenusGroup', 'SpeciesGroup']
    panels:
      - - - panel:inaturalist
