taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:descendants
          - panel:nomenclature

        - - id: panel:map
            bind:
              cluster: false
          - panel:type
          - panel:type-specimen
          - panel:etymology
          - panel:content
          - panel:nomenclature-references
          - panel:statistics
