issue_trackers:
  - label: Data
    description: Report missing information, e.g., taxon names, combinations, citations, or incorrect data. The issue could also be reported by email to Dmitry Dmitriev.
    url: https://github.com/sfg-taxonpages/hoppers/issues/new

  - label: Website
    description: Report if a link, panel, or any other feature of the website is not working as expected, as well as any suggestions on the website improvement.
    url: https://github.com/SpeciesFileGroup/taxonpages/issues/new/choose
